// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source=interface.go -destination=mock_interface_.go -package=user
//

// Package user is a generated GoMock package.
package user

import (
	models "ThreeLayeredArchitecture/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
	gofr "gofr.dev/pkg/gofr"
)

// MockuserStoreInterface is a mock of userStoreInterface interface.
type MockuserStoreInterface struct {
	ctrl     *gomock.Controller
	recorder *MockuserStoreInterfaceMockRecorder
	isgomock struct{}
}

// MockuserStoreInterfaceMockRecorder is the mock recorder for MockuserStoreInterface.
type MockuserStoreInterfaceMockRecorder struct {
	mock *MockuserStoreInterface
}

// NewMockuserStoreInterface creates a new mock instance.
func NewMockuserStoreInterface(ctrl *gomock.Controller) *MockuserStoreInterface {
	mock := &MockuserStoreInterface{ctrl: ctrl}
	mock.recorder = &MockuserStoreInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserStoreInterface) EXPECT() *MockuserStoreInterfaceMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *MockuserStoreInterface) CreateUser(ctx *gofr.Context, user models.User) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *MockuserStoreInterfaceMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*MockuserStoreInterface)(nil).CreateUser), ctx, user)
}

// GetAllUsers mocks base method.
func (m *MockuserStoreInterface) GetAllUsers(ctx *gofr.Context) ([]models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllUsers", ctx)
	ret0, _ := ret[0].([]models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllUsers indicates an expected call of GetAllUsers.
func (mr *MockuserStoreInterfaceMockRecorder) GetAllUsers(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllUsers", reflect.TypeOf((*MockuserStoreInterface)(nil).GetAllUsers), ctx)
}

// GetUserByID mocks base method.
func (m *MockuserStoreInterface) GetUserByID(ctx *gofr.Context, id int) (models.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByID", ctx, id)
	ret0, _ := ret[0].(models.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByID indicates an expected call of GetUserByID.
func (mr *MockuserStoreInterfaceMockRecorder) GetUserByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByID", reflect.TypeOf((*MockuserStoreInterface)(nil).GetUserByID), ctx, id)
}
