// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source interface.go -destination=mock_interface.go -package=task
//

// Package task is a generated GoMock package.
package task

import (
	models "ThreeLayeredArchitecture/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTaskServiceInterface is a mock of TaskServiceInterface interface.
type MockTaskServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTaskServiceInterfaceMockRecorder
	isgomock struct{}
}

// MockTaskServiceInterfaceMockRecorder is the mock recorder for MockTaskServiceInterface.
type MockTaskServiceInterfaceMockRecorder struct {
	mock *MockTaskServiceInterface
}

// NewMockTaskServiceInterface creates a new mock instance.
func NewMockTaskServiceInterface(ctrl *gomock.Controller) *MockTaskServiceInterface {
	mock := &MockTaskServiceInterface{ctrl: ctrl}
	mock.recorder = &MockTaskServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskServiceInterface) EXPECT() *MockTaskServiceInterfaceMockRecorder {
	return m.recorder
}

// CompleteTask mocks base method.
func (m *MockTaskServiceInterface) CompleteTask(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompleteTask", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompleteTask indicates an expected call of CompleteTask.
func (mr *MockTaskServiceInterfaceMockRecorder) CompleteTask(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompleteTask", reflect.TypeOf((*MockTaskServiceInterface)(nil).CompleteTask), id)
}

// CreateTask mocks base method.
func (m *MockTaskServiceInterface) CreateTask(description string) (models.MYTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", description)
	ret0, _ := ret[0].(models.MYTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTaskServiceInterfaceMockRecorder) CreateTask(description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTaskServiceInterface)(nil).CreateTask), description)
}

// DeleteTask mocks base method.
func (m *MockTaskServiceInterface) DeleteTask(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockTaskServiceInterfaceMockRecorder) DeleteTask(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockTaskServiceInterface)(nil).DeleteTask), id)
}

// GetPendingTasks mocks base method.
func (m *MockTaskServiceInterface) GetPendingTasks() ([]models.MYTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingTasks")
	ret0, _ := ret[0].([]models.MYTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingTasks indicates an expected call of GetPendingTasks.
func (mr *MockTaskServiceInterfaceMockRecorder) GetPendingTasks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingTasks", reflect.TypeOf((*MockTaskServiceInterface)(nil).GetPendingTasks))
}

// GetTask mocks base method.
func (m *MockTaskServiceInterface) GetTask(id int) (models.MYTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTask", id)
	ret0, _ := ret[0].(models.MYTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTask indicates an expected call of GetTask.
func (mr *MockTaskServiceInterfaceMockRecorder) GetTask(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTask", reflect.TypeOf((*MockTaskServiceInterface)(nil).GetTask), id)
}
