// Code generated by MockGen. DO NOT EDIT.
// Source: interface.go
//
// Generated by this command:
//
//	mockgen -source interface.go -destination=mock_interface.go -package=task
//

// Package task is a generated GoMock package.
package task

import (
	models "ThreeLayeredArchitecture/models"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTaskStoreInterface is a mock of TaskStoreInterface interface.
type MockTaskStoreInterface struct {
	ctrl     *gomock.Controller
	recorder *MockTaskStoreInterfaceMockRecorder
	isgomock struct{}
}

// MockTaskStoreInterfaceMockRecorder is the mock recorder for MockTaskStoreInterface.
type MockTaskStoreInterfaceMockRecorder struct {
	mock *MockTaskStoreInterface
}

// NewMockTaskStoreInterface creates a new mock instance.
func NewMockTaskStoreInterface(ctrl *gomock.Controller) *MockTaskStoreInterface {
	mock := &MockTaskStoreInterface{ctrl: ctrl}
	mock.recorder = &MockTaskStoreInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskStoreInterface) EXPECT() *MockTaskStoreInterfaceMockRecorder {
	return m.recorder
}

// CreateTask mocks base method.
func (m *MockTaskStoreInterface) CreateTask(description string) (models.MYTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTask", description)
	ret0, _ := ret[0].(models.MYTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTask indicates an expected call of CreateTask.
func (mr *MockTaskStoreInterfaceMockRecorder) CreateTask(description any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTask", reflect.TypeOf((*MockTaskStoreInterface)(nil).CreateTask), description)
}

// DeleteTask mocks base method.
func (m *MockTaskStoreInterface) DeleteTask(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTask", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTask indicates an expected call of DeleteTask.
func (mr *MockTaskStoreInterfaceMockRecorder) DeleteTask(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTask", reflect.TypeOf((*MockTaskStoreInterface)(nil).DeleteTask), id)
}

// GetPendingTasks mocks base method.
func (m *MockTaskStoreInterface) GetPendingTasks() ([]models.MYTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingTasks")
	ret0, _ := ret[0].([]models.MYTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingTasks indicates an expected call of GetPendingTasks.
func (mr *MockTaskStoreInterfaceMockRecorder) GetPendingTasks() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingTasks", reflect.TypeOf((*MockTaskStoreInterface)(nil).GetPendingTasks))
}

// GetTaskByID mocks base method.
func (m *MockTaskStoreInterface) GetTaskByID(id int) (models.MYTask, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTaskByID", id)
	ret0, _ := ret[0].(models.MYTask)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTaskByID indicates an expected call of GetTaskByID.
func (mr *MockTaskStoreInterfaceMockRecorder) GetTaskByID(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTaskByID", reflect.TypeOf((*MockTaskStoreInterface)(nil).GetTaskByID), id)
}

// MarkTaskCompleted mocks base method.
func (m *MockTaskStoreInterface) MarkTaskCompleted(id int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkTaskCompleted", id)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkTaskCompleted indicates an expected call of MarkTaskCompleted.
func (mr *MockTaskStoreInterfaceMockRecorder) MarkTaskCompleted(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkTaskCompleted", reflect.TypeOf((*MockTaskStoreInterface)(nil).MarkTaskCompleted), id)
}
