apiVersion: v1
kind: ConfigMap
metadata:
  name: app-env
data:
  DB_HOST: "{{ .Values.config.DB_HOST }}"
  DB_USER: "{{ .Values.config.DB_USER }}"
  DB_PASSWORD: "{{ .Values.config.DB_PASSWORD }}"
  DB_NAME: "{{ .Values.config.DB_NAME }}"
  DB_PORT: "{{ .Values.config.DB_PORT }}"
  DB_DIALECT: "{{ .Values.config.DB_DIALECT }}"
  DB_CHARSET: "{{ .Values.config.DB_CHARSET }}"
